AllCops:
   TargetRubyVersion: 2.2
   TargetRailsVersion: 4.2
   Exclude:
     - '*.spec'
     - 'Rakefile'

Rails:
  Enabled: true

Rails/ActionFilter:
  EnforcedStyle: action

# Don't enforce documentation
Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 40

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Performance/FixedSize:
  Exclude:
    - 'test/**/*'

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'

Naming/FileName:
  Exclude:
      - 'db/seeds.d/*'

Style/WordArray:
  Enabled: false

Style/RescueModifier:
  Enabled: false

# Support both ruby19 and hash_rockets
Style/HashSyntax:
  Enabled: false
  SupportedStyles:
    - ruby19
    - hash_rockets

Metrics/LineLength:
  Max: 190

Style/SymbolArray:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
