name: CI
on: [push, pull_request]
env:
  FOREMAN_PLUGIN_NAME: foreman_rescue
jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5
      - name: Setup
        run: |
          gem install bundler
          bundle install --jobs=3 --retry=3
      - name: Run rubocop
        run: bundle exec rubocop
  test:
    runs-on: ubuntu-latest
    needs: rubocop
    services:
      postgres:
        image: postgres:12.1
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      fail-fast: false
      matrix:
        foreman-core-branch: [1.21-stable, 1.22-stable, 1.23-stable, 1.24-stable, 2.0-stable, develop]
        ruby-version: [2.4, 2.5, 2.6]
        exclude:
          - foreman-core-branch: 2.0-stable
            ruby-version: 2.4
          - foreman-core-branch: develop
            ruby-version: 2.4
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'theforeman/foreman'
          ref: ${{ matrix.foreman-core-branch }}
      - uses: actions/checkout@v2
        with:
          path: ${{ env.FOREMAN_PLUGIN_NAME }}
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version:  10
      - name: Setup Foreman Plugin
        uses: kamils-iRonin/setup-foreman-plugin@master
        with:
          plugin-name: ${{ env.FOREMAN_PLUGIN_NAME }}
      - name: Run plugin tests
        run: bundle exec rake test:${FOREMAN_PLUGIN_NAME}
